Akd2gProductionMode/Controllers/GetKeyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Akd2gProductionMode.Controllers
{
    public class GetKeyController : Controller
    {
        // GET: GetKey
        public ActionResult Index()
        {
            return View();
        }
    }
}

Akd2gProductionMode/Views/Claims/Index.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sign in with Microsoft Sample</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet"
          type="text/css" />
</head>
<body style="padding:50px">
    <h3>Main Claims:</h3>
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <td>Name</td>
            <td>@ViewBag.Name</td>
        </tr>
        <tr>
            <td>Username</td>
            <td>@ViewBag.Username</td>
        </tr>
        <tr>
            <td>Subject</td>
            <td>@ViewBag.Subject</td>
        </tr>
        <tr>
            <td>TenantId</td>
            <td>@ViewBag.TenantId</td>
        </tr>
    </table>
    <br />
    <h3>All Claims:</h3>
    <table class="table table-striped table-bordered table-hover table-condensed">
        @foreach (var claim in
        System.Security.Claims.ClaimsPrincipal.Current.Claims)
        {
            <tr>
                <td>@claim.Type</td>
                <td>@claim.Value</td>
            </tr>
        }
    </table>
    <br />
    <br />
    @Html.ActionLink("Sign out", "SignOut", "Home", null, new
    {
        @class = "btn btn - primary" })
</body>
</html>

Akd2gProductionMode/Views/GetKey/Index.cshtml
@{
    ViewBag.Title = "Akd2gProductionMode";
}

<h2>Akd2g Production Mode</h2>
<form method="post">
    <label for="codeInput">Hash Code:</label>
    <input name="codeInput" id="codeInput" />
    <br /><button tyoe="submit">Get Production Code</button>
</form>

Akd2gProductionMode/Views/Home/Index.cshtml
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sign in with Microsoft Guide</title>
</head>
<body>
    @if (!Request.IsAuthenticated)
    {
        <!-- If the user is not authenticated, display the sign-in button -->
        <a href="@Url.Action("SignIn", "Home")" style="text-decoration: none;">
            <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="300px" height="50px" viewBox="0 0 3278 522" class="SignInButton">
            <style type="text/css">
                .fil0:hover {
                    fill: #4B4B4B;
                }

                .fnt0 {
                    font-size: 260px;
                    font-family: 'Segoe UI Semibold', 'Segoe UI';
                    text-decoration: none;
                }
</style>
            <rect class="fil0" x="2" y="2" width="3174" height="517" fill="black" />
            <rect x="150" y="129" width="122" height="122" fill="#F35325" />
            <rect x="284" y="129" width="122" height="122" fill="#81BC06" />
            <rect x="150" y="263" width="122" height="122" fill="#05A6F0" />
            <rect x="284" y="263" width="122" height="122" fill="#FFBA08" />
            <text x="470" y="357" fill="white" class="fnt0">Sign in with Microsoft</text>
        </svg>
        </a>
    }
    else
    {
        <span><br />Hello @System.Security.Claims.ClaimsPrincipal.Current.FindFirst("name").Value;</span>
        <br /><br />
        @Html.ActionLink("Get Production Mode Key", "Index", "GetKey")
        <br /><br />
        @Html.ActionLink("Sign out", "SignOut", "Home")
    }
    @if (!string.IsNullOrWhiteSpace(Request.QueryString["errormessage"]))
    {
        <div style="background-color:red;color:white;font-weight: bold;">Error: @Request.QueryString["errormessage"]</div>
    }
</body>
</html>